### ISSUE TITLE
Sans serif font in pagination

### ISSUE THREAD

**Issue by Lamera** [vojtechkral/bard#16] opened 2022-12-19 20:54 UTC
After setting the variable `sans_font` to true in `bard.toml` the pagination is still serif. How do I correct this?

**Comment by vojtechkral** [comment] 2022-12-19 22:26
Yeah and the ToC stays serif too... Thanks for the report, will fix...

**Comment by vojtechkral** [comment] 2022-12-19 22:47
This is the fix I used: 3f733b13b0347126803347d11644557d09b7ff9b

Pls lmk if that works for you and if yes I'll merge that to main...

**Comment by Lamera** [comment] 2022-12-19 22:58
I tried to implement your fix.
I get this error:
![grafik](https://user-images.githubusercontent.com/19840658/208542842-60f21d95-b136-4e73-b57d-5970a67f029a.png)

**Comment by Lamera** [comment] 2022-12-19 23:02
Oh wait, @vojtechkral ! This was using the `./bard watch` command. After quitting and `./bard make` it did work for the ToC. But the pagination numbers on the pages itself are still serif.

**Comment by vojtechkral** [comment] 2022-12-19 23:35
Can you share your `%% Page style / pagination` section?

**Comment by Lamera** [comment] 2022-12-26 16:44
Sorry for the late reply. Of course:
```hbs
%% Page style / pagination
\makepagestyle{songs}
\newcommand\ThePage\{{ {{~#if output.sans_font }}\sffamily{{/if}}\thepage}}
% Hack: Right pagination is moved right by using the margin
\makeoddfoot{songs}{}{}{\marginnote{\hspace{2mm}$\ThePage$}}
% Hack: Left pagination is moved left with a kern
\makeevenfoot{songs}{\kern-8mm$\ThePage$}{}{}
% Patch cleardoublepage to not get blank pages after title & contents pages:
\renewcommand\cleardoublepage{\clearpage}```

**Comment by vojtechkral** [comment] 2022-12-26 21:00
@Lamera ok, you probably need to remove those dollars - in the default template the math mode (`$`) is only used to get the angle brackets.

**Comment by Lamera** [comment] 2022-12-26 22:35
@vojtechkral Thanks, that worked for me.
How are manually changes on the `pdf.hbs` being handled in the future?
I saw you added a version check: `{{~ version_check "1.1.0" ~}}`
I have a bunch of custom stuff, that gets overridden in case of an update, right?
I thought about a simpler way to set custom stuff in a separate file. But I think this not (so easily) possible because the document is like a build plan from beginning until the end ...

**Comment by vojtechkral** [comment] 2022-12-27 20:55
@Lamera if you have your own template `.hbs` file, this will never get overriden. The purpose of the version check is to warn you in case in the future `bard` changes the shape of data that is fed into the templates (the "AST").

I did think about this but I didn't find a good solution - like you said, the template is one cohesive unit that is hard to break up. I'm afraid template upgrading will always have to be a manual process unfortunatelly.

I am considering adding a subcommand that could print a diff of your template versus the default one. But this would be done after 2.0.

**Comment by vojtechkral** [comment] 2022-12-28 23:08
Closing as the problem is sovled.

BTW. I have removed the angle brackets from page numbers in the default templates, it's a bit unusual I suppose.

**Closed by vojtechkral** 2022-12-28 23:08 UTC
